# Generated by Django 5.0.1 on 2024-03-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingsite', '0003_product_old_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('pincode', models.CharField(max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image_10',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_8',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_9',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
    ]
