# Generated by Django 5.0.1 on 2024-03-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingsite', '0004_orders_product_image_10_product_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, upload_to='clothingsite/images'),
        ),
    ]
