# Generated by Django 5.0.1 on 2024-03-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingsite', '0006_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
