# Generated by Django 5.0.1 on 2024-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothingsite', '0011_alter_product_options_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='price_adjustment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
